version: 1
services:
  - type: web
    name: MAG Trainer
    env: python
    plan: free
    buildCommand: conda env create -f environment.yml
    startCommand: conda run -n MAGTrainer python app.py
    autoDeploy: true
    restartPolicy: always