version: 1
services:
  - type: web
    name: MAG Trainer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    restartPolicy: always